In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import keras
from keras.models import Sequential
from keras.layers import SimpleRNN, Bidirectional, LSTM, GRU
from keras.layers import Dense, Activation, Dropout
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.utils import shuffle
import random
from keras.utils import get_file
from keras.optimizers import RMSprop

In [75]:
raw_text = open('holmes.txt').read().lower()

In [76]:
raw_text = raw_text[1302:50000]
raw_text

' his eyes she eclipses\nand predominates the whole of her sex. it was not that he felt\nany emotion akin to love for irene adler. all emotions, and that\none particularly, were abhorrent to his cold, precise but\nadmirably balanced mind. he was, i take it, the most perfect\nreasoning and observing machine that the world has seen, but as a\nlover he would have placed himself in a false position. he never\nspoke of the softer passions, save with a gibe and a sneer. they\nwere admirable things for the observer--excellent for drawing the\nveil from men\'s motives and actions. but for the trained reasoner\nto admit such intrusions into his own delicate and finely\nadjusted temperament was to introduce a distracting factor which\nmight throw a doubt upon all his mental results. grit in a\nsensitive instrument, or a crack in one of his own high-power\nlenses, would not be more disturbing than a strong emotion in a\nnature such as his. and yet there was but one woman to him, and\nthat woman w

In [77]:
not_imp = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '!', '@', '#', '$', '%', '^', '&',
           '*', '(', ')', '-', '_', '?', '/', '"', "'", '~', '`', ':', ';', '¢', '©', '\xa0', 
          'ã', '¨', '.', ',', ' ']
for ch in not_imp:
    if ch in raw_text:
        raw_text = raw_text.replace(ch, ' ')
print(set(raw_text))

{'s', 't', 'h', 'r', 'm', 'k', 'c', 'n', 'o', 'g', 'l', 'u', 'q', 'v', 'z', 'd', 'j', 'a', 'p', 'f', 'e', ' ', 'x', 'w', '\n', 'y', 'b', 'i'}


In [78]:
raw_text = raw_text.strip()

In [82]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [83]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([raw_text])

In [84]:
tokenizer.word_index

{'the': 1,
 'i': 2,
 'and': 3,
 'to': 4,
 'of': 5,
 'a': 6,
 'in': 7,
 'it': 8,
 'you': 9,
 'was': 10,
 'he': 11,
 'that': 12,
 'his': 13,
 'my': 14,
 'is': 15,
 'with': 16,
 'she': 17,
 'have': 18,
 'at': 19,
 'not': 20,
 'had': 21,
 'as': 22,
 'which': 23,
 'be': 24,
 'but': 25,
 'me': 26,
 'for': 27,
 'holmes': 28,
 'her': 29,
 'from': 30,
 'your': 31,
 'will': 32,
 'we': 33,
 'then': 34,
 'this': 35,
 'there': 36,
 'said': 37,
 'into': 38,
 'by': 39,
 'when': 40,
 'an': 41,
 'up': 42,
 'been': 43,
 'what': 44,
 'all': 45,
 'on': 46,
 'who': 47,
 'one': 48,
 'do': 49,
 'upon': 50,
 'so': 51,
 'were': 52,
 'out': 53,
 'very': 54,
 'if': 55,
 'could': 56,
 'are': 57,
 'has': 58,
 'him': 59,
 'am': 60,
 'down': 61,
 'man': 62,
 's': 63,
 'or': 64,
 'how': 65,
 'room': 66,
 'may': 67,
 'photograph': 68,
 'would': 69,
 'own': 70,
 'must': 71,
 'know': 72,
 'street': 73,
 'now': 74,
 'majesty': 75,
 'more': 76,
 'no': 77,
 'king': 78,
 'they': 79,
 'little': 80,
 'see': 81,
 'before': 82,

In [79]:
text = raw_text.split('\n')

In [80]:
for i in text:
    if i == '':
        text.remove(i)

In [81]:
for i in text:
    i = i.strip()

In [48]:
text

['his eyes she eclipses',
 'and predominates the whole of her sex  it was not that he felt',
 'any emotion akin to love for irene adler  all emotions  and that',
 'one particularly  were abhorrent to his cold  precise but',
 'admirably balanced mind  he was  i take it  the most perfect',
 'reasoning and observing machine that the world has seen  but as a',
 'lover he would have placed himself in a false position  he never',
 'spoke of the softer passions  save with a gibe and a sneer  they',
 'were admirable things for the observer  excellent for drawing the',
 'veil from men s motives and actions  but for the trained reasoner',
 'to admit such intrusions into his own delicate and finely',
 'adjusted temperament was to introduce a distracting factor which',
 'might throw a doubt upon all his mental results  grit in a',
 'sensitive instrument  or a crack in one of his own high power',
 'lenses  would not be more disturbing than a strong emotion in a',
 'nature such as his  and yet there

In [85]:
input_sequences = []
for sent in text:
    tokenized_sent = tokenizer.texts_to_sequences([sent])[0]
    for i in range(1, len(tokenized_sent)):
        input_sequences.append(tokenized_sent[:i+1])

In [86]:
input_sequences

[[13, 117],
 [13, 117, 17],
 [13, 117, 17, 805],
 [3, 806],
 [3, 806, 1],
 [3, 806, 1, 262],
 [3, 806, 1, 262, 5],
 [3, 806, 1, 262, 5, 29],
 [3, 806, 1, 262, 5, 29, 807],
 [3, 806, 1, 262, 5, 29, 807, 8],
 [3, 806, 1, 262, 5, 29, 807, 8, 10],
 [3, 806, 1, 262, 5, 29, 807, 8, 10, 20],
 [3, 806, 1, 262, 5, 29, 807, 8, 10, 20, 12],
 [3, 806, 1, 262, 5, 29, 807, 8, 10, 20, 12, 11],
 [3, 806, 1, 262, 5, 29, 807, 8, 10, 20, 12, 11, 491],
 [263, 492],
 [263, 492, 493],
 [263, 492, 493, 4],
 [263, 492, 493, 4, 184],
 [263, 492, 493, 4, 184, 27],
 [263, 492, 493, 4, 184, 27, 84],
 [263, 492, 493, 4, 184, 27, 84, 91],
 [263, 492, 493, 4, 184, 27, 84, 91, 45],
 [263, 492, 493, 4, 184, 27, 84, 91, 45, 808],
 [263, 492, 493, 4, 184, 27, 84, 91, 45, 808, 3],
 [263, 492, 493, 4, 184, 27, 84, 91, 45, 808, 3, 12],
 [48, 494],
 [48, 494, 52],
 [48, 494, 52, 809],
 [48, 494, 52, 809, 4],
 [48, 494, 52, 809, 4, 13],
 [48, 494, 52, 809, 4, 13, 495],
 [48, 494, 52, 809, 4, 13, 495, 810],
 [48, 494, 52, 809

In [87]:
max_len = max([len(x) for x in input_sequences])
max_len

16

In [89]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding = 'pre')

In [90]:
padded_input_sequences

array([[   0,    0,    0, ...,    0,   13,  117],
       [   0,    0,    0, ...,   13,  117,   17],
       [   0,    0,    0, ...,  117,   17,  805],
       ...,
       [   0,    0,    0, ...,  121,   36,   15],
       [   0,    0,    0, ...,   36,   15,   66],
       [   0,    0,    0, ...,   15,   66, 1992]])

In [91]:
X = padded_input_sequences[:,:-1]
X

array([[  0,   0,   0, ...,   0,   0,  13],
       [  0,   0,   0, ...,   0,  13, 117],
       [  0,   0,   0, ...,  13, 117,  17],
       ...,
       [  0,   0,   0, ...,  95, 121,  36],
       [  0,   0,   0, ..., 121,  36,  15],
       [  0,   0,   0, ...,  36,  15,  66]])

In [93]:
y = padded_input_sequences[:, -1]
y

array([ 117,   17,  805, ...,   15,   66, 1992])

In [94]:
X.shape

(8145, 15)

In [95]:
y.shape

(8145,)

In [97]:
len(tokenizer.word_index)

1992

In [98]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes = len(tokenizer.word_index)+1)

In [99]:
y.shape

(8145, 1993)

In [100]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [101]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [109]:
model = Sequential()
model.add(Embedding(1993, 100, input_length = 15))
model.add(LSTM(150))
model.add(Dense(1993, activation = 'softmax'))

In [110]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [111]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 15, 100)           199300    
                                                                 
 lstm_2 (LSTM)               (None, 150)               150600    
                                                                 
 dense_2 (Dense)             (None, 1993)              300943    
                                                                 
Total params: 650843 (2.48 MB)
Trainable params: 650843 (2.48 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [113]:
model.fit(X, y, epochs = 100)

Epoch 1/100
255/255 [==============================] - 4s 14ms/step - loss: 4.2261 - accuracy: 0.1810
Epoch 2/100
255/255 [==============================] - 4s 14ms/step - loss: 4.0438 - accuracy: 0.1980
Epoch 3/100
255/255 [==============================] - 4s 14ms/step - loss: 3.8636 - accuracy: 0.2194
Epoch 4/100
255/255 [==============================] - 4s 15ms/step - loss: 3.6867 - accuracy: 0.2409
Epoch 5/100
255/255 [==============================] - 4s 15ms/step - loss: 3.5118 - accuracy: 0.2663
Epoch 6/100
255/255 [==============================] - 4s 15ms/step - loss: 3.3413 - accuracy: 0.2900
Epoch 7/100
255/255 [==============================] - 4s 15ms/step - loss: 3.1749 - accuracy: 0.3198
Epoch 8/100
255/255 [==============================] - 4s 15ms/step - loss: 3.0105 - accuracy: 0.3494
Epoch 9/100
255/255 [==============================] - 4s 15ms/step - loss: 2.8484 - accuracy: 0.3833
Epoch 10/100
255/255 [==============================] - 4s 15ms/step - loss: 2.691

255/255 [==============================] - 4s 15ms/step - loss: 0.2163 - accuracy: 0.9281
Epoch 81/100
255/255 [==============================] - 4s 15ms/step - loss: 0.1949 - accuracy: 0.9314
Epoch 82/100
255/255 [==============================] - 4s 15ms/step - loss: 0.1875 - accuracy: 0.9299
Epoch 83/100
255/255 [==============================] - 4s 15ms/step - loss: 0.1838 - accuracy: 0.9305
Epoch 84/100
255/255 [==============================] - 4s 14ms/step - loss: 0.1832 - accuracy: 0.9300
Epoch 85/100
255/255 [==============================] - 4s 15ms/step - loss: 0.1835 - accuracy: 0.9309
Epoch 86/100
255/255 [==============================] - 4s 15ms/step - loss: 0.1822 - accuracy: 0.9317
Epoch 87/100
255/255 [==============================] - 4s 15ms/step - loss: 0.1823 - accuracy: 0.9308
Epoch 88/100
255/255 [==============================] - 4s 15ms/step - loss: 0.1813 - accuracy: 0.9339
Epoch 89/100
255/255 [==============================] - 4s 15ms/step - loss: 0.1821 - 

In [133]:
text_pred = 'i had'

for i in range(10):
    token_text = tokenizer.texts_to_sequences([text_pred])[0]
    padded_token_text = pad_sequences([token_text], maxlen = 15, padding = 'pre')

    import numpy as np
    pos = np.argmax(model.predict(padded_token_text))

    for word, index in tokenizer.word_index.items():
        if index == pos:
            text_pred = text_pred + " " + word
            print(text_pred)

1/1 [==============================] - 0s 31ms/step
i had seen
1/1 [==============================] - 0s 29ms/step
i had seen little
1/1 [==============================] - 0s 31ms/step
i had seen little of
1/1 [==============================] - 0s 31ms/step
i had seen little of holmes
1/1 [==============================] - 0s 37ms/step
i had seen little of holmes lately
1/1 [==============================] - 0s 30ms/step
i had seen little of holmes lately my
1/1 [==============================] - 0s 36ms/step
i had seen little of holmes lately my marriage
1/1 [==============================] - 0s 30ms/step
i had seen little of holmes lately my marriage had
1/1 [==============================] - 0s 32ms/step
i had seen little of holmes lately my marriage had drifted
1/1 [==============================] - 0s 37ms/step
i had seen little of holmes lately my marriage had drifted us
